version: 2

pipelines:
  pr:
    stages:
      - id: build-backend
        workflow: .github/workflows/deploy-build-backend.yml

      - id: build-frontend
        workflow: .github/workflows/deploy-build-frontend.yml

      - id: docker-publish
        workflow: .github/workflows/deploy-docker-publish.yml
        needs:
          - build-backend
