name: PR Pipeline

on:
  pull_request:
    branches: [master]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write
  statuses: write

jobs:
  run-pipeline:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: aeswibon/pipeline-compose-run@v1.17.1
        with:
          pipeline_file: .github/pipelines/deploy.yml
          github_token: ${{ github.token }}
